### ISSUE TITLE
Error "Unexpected token 'export'" on import

### ISSUE THREAD

**Issue by webbster-dev** [typebot-io/typebot-js#1]
On a fresh install, whenever importing the typebot library in React (NextJS) it throws an error.

I checked the difference in `index.js` between versions, in `v2.0.0` it works but on the latest it does not.

Error: 

```
/Users/thomas/development/projects/project-1/node_modules/typebot-js/dist/index.js:380
export { getBubbleActions, getPopupActions, initBubble, initContainer, initPopup, localStorageKeys };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.typebot-js (/Users/thomas/development/projects/project-1/.next/server/pages/_app.js:106:18)
    at __webpack_require__ (/Users/thomas/development/projects/project-1/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.jsx:9:68)
/Users/thomas/development/projects/project-1/node_modules/typebot-js/dist/index.js:380
```

Using it like this:

```
import { initBubble } from 'typebot-js';

useEffect(() => {
    initBubble({
      publishId: 'project',
      backgroundColor: '#ffffff',
      proactiveMessage: {
        textContent: 'Hey!',
        rememberClose: true,
        delay: 5000,
      },
      button: { color: '#2edcaf' },
    });
  }, []);
```

Importing like this (as shown in the docs) does not make a difference:

```
import Typebot from 'typebot-js';

// or

import * as Typebot from 'typebot-js';
```

This may be a simple fix, I changed this line in the compiled code:

`export { getBubbleActions, getPopupActions, initBubble, initContainer, initPopup, localStorageKeys };`

to:

`module.exports = { getBubbleActions, getPopupActions, initBubble, initContainer, initPopup, localStorageKeys };`

Or I might be doing something wrong here, in either way would love some clarification. Thanks!

**Comment by baptisteArno** [comment]
Fixed on `v2.0.20` 😀
